[package]
name = "jyafn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jyafn"
path = "src/lib.rs"


[dependencies]
bincode = "1.3.3"
byte-slice-cast = "1.2.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
memmap = "0.7.0"
object = "0.34.0"
qbe = { path = "../vendored/qbe-rs" }
serde = { version = "1.0.197", features = ["rc"] }
serde_derive = "1.0.197"
serde_json = "1.0.115"
tempfile = "3.10.1"
thiserror = "1.0.58"
typetag = "0.2.16"
