[package]
name = "jyafn_ppca"
version = "0.1.0"
edition = "2021"


[lib]
name = "jyafn_ppca"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
jyafn-ext = { path = "../.." }
nalgebra = "0.32.6"
ppca = "0.5.0"
