[package]
name = "cjyafn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doc = false
name = "cjyafn"
crate-type = ["staticlib"]

[dependencies]
jyafn = { path = "../jyafn" }
serde_json = "1.0.115"

[build-dependencies]
cbindgen = "0.26.0"
