name: Build Python wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Prepare maturin build
      run: make qbe
    - name: Maturin build
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release
        container: manylinux2014
        working-directory: jyafn-python
    - name: ls
      run: ls target/wheels
