name: Build Python wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["3.10"] #, "3.11", "3.12"]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Prepare maturin build
      run: make qbe
    - name: Maturin build
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release -i ${{ matrix.pyversion }}
        manylinux: auto
        working-directory: jyafn-python
    - name: Artifact update
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.pyversion }}
        if-no-files-found: error
        path: target/wheels/*.whl
        retention-days: 1

  release:
    needs: [build-wheel]
    runs-on: ubuntu-latest
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        pattern: wheel-*
        merge-multiple: true
    - run: ls target/wheels
